spring:
  application:
    name: gateway-zuul
server:
  port: 8082
eureka:
  client:
    service-url: 
      defaultZone: http://192.168.20.191:8761/eureka/
#      defaultZone: http://admin:password123@localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
#zuul:
#  routes:
#    hystrix:
#      path: /hystrix/**
#      service-id: movie-ribbon-hystrix
#    hystrix2:
#      path: /hystrix2/**
#      service-id: movie-ribbon-hystrix2
#      strip-prefix: false #集群movie-ribbon-hystrix2设置了context-path使用
zuul:
  routes:
    movie-ribbon-hystrix: /hystrix/**
    movie-ribbon-hystrix2: /hystrix2/**   