server:
  port: 8099
spring:  
  application:
    name: stream-pub
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.43.241:9092  #Kafka的消息中间件服务器
          auto-create-topics: true #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了
      bindings: 
        output: #stream默认提供的output
          destination: stream-demo #消息发往的目的地
          content-type: text/plain #消息发送的格式，接收端不用指定，发送端需要指定
        myOutput: #自定义消息发送output
          destination: myStream-demo
          content-type: text/plain
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.43.240:8761/eureka/
#      defaultZone: http://192.168.20.191:8761/eureka/
#      defaultZone: http://admin:123@localhost:8761/eureka/
    enabled: true
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}