server:
  port: 8099
spring:  
  datasource:
   url: jdbc:mysql://192.168.0.102:3306/jzy_cxkj_center
   username: root  
   password: 123456  
   driver-class-name: com.mysql.jdbc.Driver
   max-idle: 10
   max-wait: 10000
   min-idle: 5
   initial-size: 5
  application:
    name: movie-threadpool
  cloud:
    refresh:
      refreshable: none
mybatis:
  mapper-locations: classpath*:com/ly/*/mapper/*.xml
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.0.102:8761/eureka/
#      defaultZone: http://192.168.20.191:8761/eureka/
#      defaultZone: http://admin:123@localhost:8761/eureka/
    enabled: true
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}