spring:
  application:
    name: eureka-service
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
    
# security:
#    enabled: true
#    user:
#      name: admin
#      password: password123
#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    enabled: true
#    service-url: 
#      defaultZone: http://localhost:${server.port}/eureka/
#      defaultZone: http://admin:password123@localhost:${server.port}/eureka/
#  instance:
#    ip-address: true