server:
  port: 8762
spring:
  profiles: peer2
  application:
    name: eureka-service
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  instance:
    ip-address: true