server:
  port: 8763
spring:
  profiles: peer3
  application:
    name: eureka-service
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    ip-address: true